### ISSUE TITLE
Question on adjusting the cursorline color

### ISSUE THREAD

**Issue by femto-code** [atom-minimap/minimap-cursorline#35]
First, thank you very much for maintaining this great plugin!
I tried to edit the cursorline background color as shown in the Readme, but it did not work until now. It does not change the color.

Let me ask one another question: which is the theme / syntax theme used in the screenshot on the readme? And font? Thanks!

**Comment by UziTech** [comment]
> I tried to edit the cursorline background color as shown in the Readme, but it did not work

I think you are correct this must be something that has been broken in minimap. I'll see if I can find the issue soon.

> which is the theme / syntax theme used in the screenshot on the readme? And font? 

I do not know I was not the one who created the screenshot.

**Comment by UziTech** [comment]
This should be fixed in the latest version of minimap.
